import os
print(os.getcwd())
print(os.listdir())
os.mkdir('demo')
print(os.listdir())
print(os.path.isdir('demo'))
print(os.path.exists('test1.txt'))
print(os.path.exists('test99.txt'))
print(os.path.exists('test88.txt'))
print(os.path.exists('test77.txt'))
# os.chdir('demo')
c = os.path.join('Users\Tsubasa\PycharmProjects\SampleCode\CH001', 'test3.txt')
print(c, type(c))
d = os.path.join(os.getcwd(), 'demo', 'test.txt')
print(d, type(d))
os.rmdir('demo')
b = os.listdir()
print(b)
print(type(b))
help(os.mkdir)
